name = "LoVe"
defaultTargets = ["LoVe"]

[leanOptions]
autoImplicit = false
linter.unusedVariables = false 

[moreServerOptions]
linter.unusedTactic = false
linter.unreachableTactic = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "29f9a66d622d9bab7f419120e22bb0d2598676ab"

[[require]]
name = "autograder" 
git = "https://github.com/ZMTJQ/lean4-autograder-main-copy"
rev = "master"

[[require]]
name = "mdgen"
git = "https://github.com/Seasawher/mdgen"
rev = "116f091322ca97a8d3fafb27c3d1a24b39cbd9bb"

[[lean_lib]]
name = "LoVe"
