name = "LoVe"
defaultTargets = ["LoVe"]

[leanOptions]
autoImplicit = false
linter.unusedVariables = false 

[moreServerOptions]
linter.unusedTactic = false
linter.unreachableTactic = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "a719ba5c3115d47b68bf0497a9dd1bcbb21ea663"

[[require]]
name = "autograder" 
git = "https://github.com/ZMTJQ/lean4-autograder-main-copy.git" 
rev = "428c8ecb9193ccea0bdeab0d976468ccdbed9e1c"

[[require]]
name = "mdgen"
git = "https://github.com/Seasawher/mdgen"
rev = "bdfc2e355fbd5003be7094b3c99ff9d833aff7da"

[[lean_lib]]
name = "LoVe"
