name: Lean Autograder

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      # Checkout the student's code (i.e., this repo)
      - uses: actions/checkout@v3

      # Install Lean using elan (Lean's version manager)
      - name: Install Lean via Elan
        run: |
          curl -s https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq  
        
      # Run lake to build the project (including the autograder)
      - name: Build with lake
        run: |
          lake update autograder
          lake exe cache get
          lake build

      # Run the autograder with the student's submission
      - name: Run Lean Autograder
        run: |
          lake exe autograder --local LoVe/Homework/Homework1.lean LoVe/Homework/Homework1.lean
        
      # Debug: Show contents if needed
      - name: Show results.json
        run: cat results.json

      # Extract Gradescope-compatible 'tests' field
      - name: Format Gradescope JSON for GitHub Classroom
        run: |
          mkdir -p .results
          jq '.tests' results.json > .results/results.json
          
      # Upload for manual debug (optional)   
      - name: Upload results.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-json
          path: /home/runner/work/fpv2024_copy/fpv2024_copy/results.json

    
