name: Lean Autograder

on: [push, pull_request]

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      # Checkout the student's code (i.e., this repo)
      - uses: actions/checkout@v3

      # Install Lean using elan (Lean's version manager)
      - name: Install Lean via Elan
        run: |
          curl -s https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | bash -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          
      - name: Force Lean version
        run: |
          echo "leanprover/lean4:4.15.0" > lean-toolchain
          lake update autograder 
          lake update mathlib
          lake update mdgen
          
      # Run lake to build the project (including the autograder)
      - name: Build with lake
        run: |
          lake exe cache get
          lake build

      # Run the autograder with the student's submission
      - name: Run Lean Autograder
        run: |
          lake exe autograder --local LoVe/Homework/Homework1.lean LoVe/Homework/Homework1.lean
     
      - name: Debug Find and inspect results.json
        run: |
          find . -name "results.json" -exec ls -lh {} \;
          cat ./results.json || echo "results.json not found"
          
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
  
      - name: Format Gradescope JSON for GitHub Classroom
        run: |
          mkdir -p .results
          jq '.tests' results.json > .results/results.json
